[project]
name = "deep-rl-with-gym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[classic-control]>=1.2.3",
    "matplotlib>=3.10.8",
    "pygame>=2.6.1",
    "tqdm>=4.67.3",
]
